version: "3"

services:
  opensim:
    image: opensim-gui:latest

    # Build args
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:18.04
        BUILD_CORES: 30
        USER: docker

    # Run args
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
