version: "3"

services:
  opensim:
    image: opensim-python:latest

    # Build args
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:20.04
        BUILD_CORES: 30
        USER: docker

    # Run args
    environment:
      - DISPLAY=${DISPLAY}
      - LD_LIBRARY_PATH=/opt/opensim-gui/sdk/Simbody/lib:/opt/opensim-gui/sdk/lib
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
